# Generated by Django 5.1.1 on 2024-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='permissions',
            field=models.ManyToManyField(to='group.permission'),
        ),
    ]
