# Generated by Django 5.1.1 on 2024-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_customgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
