# Generated by Django 5.1.1 on 2024-09-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_permission_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.module'),
            preserve_default=False,
        ),
    ]
