# Generated by Django 5.1.1 on 2024-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_remove_module_permissions_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
