# Generated by Django 5.1.1 on 2024-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_module_permission_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='permission',
            field=models.JSONField(default={'add': False, 'delete': False, 'update': False, 'view': True}),
        ),
    ]
