# Generated by Django 5.1.1 on 2024-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_groups_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
